2020-09-13 17:10:06,833 - instabot version: 0.117.0 (bot) - INFO - Instabot version: 0.117.0 Started
2020-09-13 17:10:06,834 - instabot version: 0.117.0 (bot) - DEBUG - Bot imported from C:\Users\ozgey\Desktop\instagram_filtre\venv\lib\site-packages\instabot\bot\bot.py
2020-09-13 17:10:06,835 - instabot version: 0.117.0 (api_login) - INFO - Not yet logged in starting: PRE-LOGIN FLOW!
2020-09-13 17:10:07,145 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/get_prefill_candidates/ returned response: <Response [200]>
2020-09-13 17:10:07,490 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: qe/sync/ returned response: <Response [200]>
2020-09-13 17:10:07,786 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: launcher/sync/ returned response: <Response [200]>
2020-09-13 17:10:08,059 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/contact_point_prefill/ returned response: <Response [200]>
2020-09-13 17:10:10,332 - instabot version: 0.117.0 (api) - DEBUG - POST to endpoint: accounts/login/ returned response: <Response [400]>
2020-09-13 17:10:10,332 - instabot version: 0.117.0 (api) - DEBUG - Responsecode indicates error; response content: b'{"message": "challenge_required", "challenge": {"url": "https://i.instagram.com/challenge/7847183430/SI63TfVseb/", "api_path": "/challenge/7847183430/SI63TfVseb/", "hide_webview_header": true, "lock": true, "logout": false, "native_flow": true}, "status": "fail", "error_type": "checkpoint_challenge_required"}'
2020-09-13 17:10:10,332 - instabot version: 0.117.0 (api) - ERROR - Request returns 400 error!
2020-09-13 17:10:10,332 - instabot version: 0.117.0 (api) - INFO - Instagram's error message: challenge_required
2020-09-13 17:10:10,334 - instabot version: 0.117.0 (api) - INFO - Error type: checkpoint_challenge_required
